# Generated by Django 4.1.5 on 2023-01-14 20:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0002_sample'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Sample',
        ),
    ]
