# Generated by Django 4.1.5 on 2023-01-15 09:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0004_tasks'),
    ]

    operations = [
        migrations.DeleteModel(
            name='tasks',
        ),
    ]
